### ISSUE TITLE
ERROR: Failed to scan for dependencies from entries

### ISSUE THREAD

**Issue by salmaissis** [whybe7/react-laravel-ecommerce#2]
```console
Error:   Failed to scan for dependencies from entries:
  C:/Users/user/Desktop/projects/cybermall/client/index.html

  X [ERROR] Failed to resolve entry for package "redux-persist". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///C:/Users/user/Desktop/projects/cybermall/client/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23384:11)

X [ERROR] Failed to resolve entry for package "redux-persist". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///C:/Users/user/Desktop/projects/cybermall/client/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23384:11)
```

**Comment by salmaissis** [comment]
![image](https://user-images.githubusercontent.com/125306967/236910123-cd085176-3c7b-4a28-89fc-e240895157cd.png)
 these errors occured when i cloned the repo and run 'npm run dev'
i have already installed all the dependencies so i don't know what's wrong

**Comment by salmaissis** [comment]
this issue solved by **cloning the repo again** and running _'npm i'_
